config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'welcome/index'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  resources :users
  resources :sessions
  resources :groups  
  resources :moves
  
  

  root 'welcome#index'

end

app/models/move.rb
class Move < ActiveRecord::Base
  
  has_ancestry
  has_many :steps
  accepts_nested_attributes_for :steps, :allow_destroy => true
  validates :name, :notes, presence: true
  validates :start_date, presence: true
  validates :distance, numericality: true
  scope :macros, -> { where(type: 'Macro') } 
  scope :mesos, -> { where(type: 'Meso') }
  scope :micros, -> { where(type: 'Micro') }
  scope :nanos, -> { where(type: 'Nano') }
  
  def as_json(*args)
    super.tap { |hash| hash["text"] = hash.delete "name" }
  end

  def self.type
    %w(Macro Meso Micro Nano)
  end

  def self.inheritance_column
    :no_such_column_because_we_dont_want_type_casting
  end
  
  def planned_distance
    planned_distance = 0
    if type == "Nano"
      planned_distance = steps.to_a.sum { |step| step.times * step.distance}
    else
      planned_distance = children.to_a.sum { |child| child.type == "Nano" ? child.distance : child.planned_distance }
    end
  end
  
  def period_length_days
    from_date = start_date.nil? ? 0 : start_date 
    to_date = end_date.nil? ? 0 : end_date
    ((to_date - from_date)/(60*60*24)).floor
  end
  
  def period_length_weeks
    (period_length_days/7).floor
  end
end


  

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]
  # before_filter :require_login

  # GET /moves
  # GET /moves.json
  def index
      @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
    @disabled_mode = true
  end

  # GET /moves/new
  def new
    @disabled_mode = false 
    if(params.has_key?(:parent_id))   
      @move = Move.new(:parent_id => params[:parent_id], :type => child_type)
    else
      @move = Move.new(:type => 'Macro')
    end
  end

  # GET /moves/1/edit
  def edit
    @disabled_mode = false
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        # format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        # format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        # format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        # format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:name, :notes, :start_date, :end_date, :distance, :duration, :type, :parent_id,
            steps_attributes: [:id, :name, :notes, :times, :distance, :duration, :intensity, :pace, :rest, :_destroy])
    end
    
    def child_type
      parent = Move.find(params[:parent_id])
      child_type = case parent.type
      when 'Macro' then 'Meso'
      when 'Meso' then 'Micro'
      when 'Micro' then 'Nano'
      else 'Invalid Type'
      end
    end
end

app/helpers/moves_helper.rb
module MovesHelper
  
  def nice_date(date)
    date.strftime("%-d/%-m/%y")
  end
end

app/views/moves/_form.html.erb
<%= nested_form_for(@move) do |f| %>
	<% if @move.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>
		  <ul>
		  <% @move.errors.full_messages.each do |message| %>
		    <li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>
	<%= f.hidden_field :parent_id %>
	<%= f.hidden_field :type %>
	<table width="80%">
		<tr>
			<td colspan="1" width="25">
			    <%= image_tag asset_path(@move.type + "-ciclo.jpg") %>
			</td>
			<td colspan="1" width="200">
			  <div class="field">
			    <%= f.label :type %><br>
			    <p><%= @move.type %></p>
			  </div>
			</td>
			<td colspan="2">
			  <div class="field">
			    <%= f.label :name %><br>
			    <%= f.text_field :name, :size => 40, disabled: @disabled_mode %>
			  </div>
			</td>
		</tr>
		<tr>
			<td colspan="4">	
			  <div class="field">
			    <%= f.label :notes %><br>
			    <%= f.text_area :notes, :cols => 80, :rows => 3, disabled: @disabled_mode %>  
			  </div>
			</td>
		</tr>
		<tr>
			<td colspan="2">
			  <div class="field">
			    <%= f.label :start_date %><br>
			    <%= f.date_select(:start_date, {:disabled => @disabled_mode, :order => [:day, :month, :year]}, {:onchange =>"refresh_lengths()"}) %>
			  </div>
			</td>
			<td colspan="2">				
			  <% if @move.type != "Nano" %>
				  <div class="field">
				    <%= f.label :end_date %><br>
				    <%= f.date_select(:end_date, {:disabled => @disabled_mode, :order => [:day, :month, :year]}, {:onchange =>"refresh_lengths()"}) %>
				  </div>
			  <% end %>
			</td>
	  	</tr>
	  	<tr>
			<td colspan="2">  		
			  <div class="field">
			    <%= f.label "period_length_days" %><br>
			    <p id="period_length_days"><%= @move.period_length_days %> days</p>
			  </div>
			</td>
			<td colspan="2">  		
			  <div class="field">
			    <%= f.label "period_length_weeks" %><br>
			    <p id="period_length_weeks"><%= @move.period_length_weeks %> weeks</p>			    
			  </div>
			</td>
	  	</tr>	  	
	  	<tr>
			<td colspan="2">  		
			  <div class="field">
			    <%= f.label :guideline_distance %><br>
			    <%= f.text_field :distance, disabled: @disabled_mode %>
			  </div>
			</td>
	  	</tr>
	  	<tr>
			<td colspan="2">  		
			  <div class="field">
			    <%= f.label :planned_distance %><br>
			    <% if @move.new_record? %>
			    	<p>N/A</p>
			    <% else %>
					<%= f.text_field :planned_distance, disabled: true %>
			  	<% end %>  	
			  </div>
			<td colspan="2">
			  <div class="field">
			  </div>
			</td>
	  	</tr>
	</table>
	<% if @move.type == "Nano" %>
	  	<table width="80%">
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Notes</th>
		      <th>Times</th>
		      <th>Distance</th>
		      <th>Duration</th>
		      <th>Intensity</th>
		      <th>Pace</th>
		      <th>Rest</th>
		    </tr>
		  </thead>
		  <tbody>
	  		<%= f.fields_for :steps %>
			<% if !@disabled_mode %>	  	
		  		<tr>
					<td colspan="4"><%= link_to_add_fields "Add Step", f, :steps %></td>
				</tr>
			<% end %>
	  	  </tbody>
		</table> 
	<% end %>
  <div class="actions">	
	<% if !@disabled_mode %>	  	
	    <%= f.submit %>
	<% end %>
  </div>
<% end %>

app/views/moves/_step_fields.html.erb
<tr>
	<td><%= f.text_field :name, size:3, disabled: @disabled_mode %></td>
	<td><%= f.text_field :notes, size:20, disabled: @disabled_mode %></td>
	<td><%= f.text_field :times, size:3, disabled: @disabled_mode %></td>
	<td><%= f.text_field :distance, size:6, disabled: @disabled_mode %></td>
	<td><%= f.text_field :duration, size:6, disabled: @disabled_mode %></td>
	<td><%= f.text_field :intensity, size:6, disabled: @disabled_mode %></td>
	<td><%= f.text_field :pace, size:6, disabled: @disabled_mode %></td>
	<td><%= f.text_field :rest, size:6, disabled: @disabled_mode %></td>
	<% if !@disabled_mode %>	
		<td><%= link_to_remove_fields "Remove", f %></td>
	<% end %>
</tr>

app/views/moves/edit.html.erb
<h1>Editing <%= @move.type %> Cycle</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<hr>
<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<h1>Listing Plans</h1>

<p id="notice"><%= notice %></p>

<div id="treebox">
	<div id="jstree"></div>
</div>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<hr>
<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<h1>Showing <%= @move.type %> Cycle</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<hr>
<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>